[package]
name = "bencher"
version = "0.3.0"
authors = ["bsdinis <baltasar.dinis@tecnico.ulisboa.pt>"]
edition = "2021"

[dependencies]
clap = "3.0"
cli-table = "0.4"
rusqlite = { version = "0.28", features = ["vtab"] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
either = "1.8"
eyre = "0.6.8"
color-eyre = "0.6.2"

[lib]
name = "bencher"
path = "src/lib.rs"

[[bin]]
name = "bencher"
path = "src/bin.rs"
