[package]
name = "bencher-lib"
version = "0.1.0"
authors = ["bsdinis <baltasar.dinis@tecnico.ulisboa.pt>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6"
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
cli-table = "0.4"
rusqlite = { version = "0.26", features = ["vtab"] }
either = "1.6"
