[package]
name = "bencher"
version = "0.2.0"
authors = ["bsdinis <baltasar.dinis@tecnico.ulisboa.pt>"]
edition = "2018"

[dependencies]
clap = "3.0"
cli-table = "0.4"
color-eyre = "0.5"
either = "1.6"
eyre = "0.6"
rusqlite = { version = "0.26", features = ["vtab"] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "1"

[lib]
name = "bencher"
path = "src/lib.rs"

[[bin]]
name = "bencher"
path = "src/bin.rs"
