[package]
name = "bencher"
version = "0.1.0"
authors = ["bsdinis <baltasar.dinis@tecnico.ulisboa.pt>"]
edition = "2018"

[dependencies]
eyre = "0.6"
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
cli-table = "0.4"
rusqlite = { version = "0.26", features = ["vtab"] }
either = "1.6"

[lib]
name = "bencher"
path = "src/lib.rs"

[[bin]]
name = "bencher"
path = "src/bin.rs"
